############################
## CHANGE THESE
############################

# baseURL: "https://github.com/CiderGuru/Blog-2024-001"
# baseURL: "https://stablemilkingstool.co.uk/public/"
baseURL: "https://blog-2024-01.netlify.app"
title: A Very Stable Blog

############################
## MISC ##
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
