############################
## Author
############################

author:
  name: A Very Stable Milking Stool
  image: author.png
  greeting: "Hello :tada:"
  icon: ":wave:"

############################
## Links
############################

links:
  - github: https://github.com/CiderGuru/Blog-2024-001
  # - website: https://www.stablemilskingstool.co.uk
  - x-twitter: https://twitter.com/MonkeyOfStool
  # - mastodon:  
  # - reddit: 
  # - telegram: 
  # - whatsapp: 
  - email: mailto:stool@stablemilkingstool.co.uk
  # - discord: 
  # - twitch: 
  # - patreon: 
  # - youtube: 
  # - keybase: 
  - bluesky: https://bsky.app/profile/stablemilkingstool.co.uk
  # - spotify: 
  # - skype: 
  amazon: https://www.amazon.co.uk/hz/wishlist/ls/1KXIMI7XMSWLS?ref_=wl_share
  paypal: https://paypal.me/JonesHoward

###############################
## OpenGraph & Twitter Cards
###############################

title: Blog-2024-001
description: "Site built with Jauntiness"
images:
  - thumbnail.png
