############################
## Author
############################

author:
  name: A Very Stable Milking Stool
  image: author.png
  greeting: "Feeding All The Memrmaids, with All The Kebabs :tada:"
  icon: ":wave:"

############################
## Links
############################

links:
  #- github: https://github.com/CiderGuru/
  # - website: https://www.stablemilskingstool.co.uk
  - bluesky: https://bsky.app/profile/stablemilkingstool.co.uk
  - x-twitter: https://twitter.com/MonkeyOfStool
  - amazon: https://www.amazon.co.uk/hz/wishlist/ls/1KXIMI7XMSWLS?ref_=wl_share
  - paypal: https://paypal.me/JonesHoward
  - email: mailto:stool@stablemilkingstool.co.uk
  # - mastodon:  
  # - reddit: 
  # - telegram: 
  # - whatsapp: 
  # - discord: 
  # - twitch: 
  # - patreon: 
  # - youtube: 
  # - keybase: 
  # - spotify: 
  # - skype: 

###############################
## OpenGraph & Twitter Cards
###############################

title: A Very Stable Blog
description: "A Site built with Jauntiness"
images:
  - thumbnail.png
